<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Appointment;
use App\Models\Receipt;
use App\Models\ReceiptItem;
use App\Models\Feedback;
use App\Models\Prescription;
use App\Models\Reservation;
use App\Models\User;

class RemoveAnalyticsTestData extends Command
{
    protected $signature = 'analytics:remove-test {--confirm : Skip confirmation prompt}';

    protected $description = 'Remove all test data generated by analytics:add-test command';

    public function handle()
    {
        $this->newLine();
        $this->warn('🗑️  Remove Analytics Test Data');
        $this->line('This will delete all data with test notes from analytics commands.');
        $this->newLine();

        // Count test data
        $testPatients = User::where('email', 'like', '%@testpatient.com')->count();
        $testAppointments = Appointment::where('notes', 'like', '%Test appointment for analytics%')->count();
        $testReceipts = Receipt::where('receipt_number', 'like', 'RCP-%')->count();
        $testReservations = Reservation::where('notes', 'like', '%Test reservation for analytics%')->count();
        $testFeedback = Feedback::where('comment', 'like', '%Test feedback for analytics%')->count();
        $testPrescriptions = Prescription::where('notes', 'like', '%Test prescription for analytics%')->count();

        $total = $testPatients + $testAppointments + $testReceipts + $testReservations + $testFeedback + $testPrescriptions;

        if ($total === 0) {
            $this->info('✅ No test data found. Nothing to delete.');
            return 0;
        }

        $this->info('📊 Found test data:');
        $this->table(
            ['Type', 'Count'],
            [
                ['Test Patients', $testPatients],
                ['Appointments', $testAppointments],
                ['Receipts', $testReceipts],
                ['Reservations', $testReservations],
                ['Feedback', $testFeedback],
                ['Prescriptions', $testPrescriptions],
                ['TOTAL', $total],
            ]
        );

        if (!$this->option('confirm')) {
            if (!$this->confirm('Are you sure you want to delete this test data?', true)) {
                $this->info('Operation cancelled.');
                return 0;
            }
        }

        $this->newLine();
        $this->info('🗑️  Deleting test data...');

        $deleted = 0;

        // Delete feedback first
        $feedbackDeleted = Feedback::where('comment', 'like', '%Test feedback for analytics%')->delete();
        $deleted += $feedbackDeleted;
        $this->line("  ✅ Deleted {$feedbackDeleted} feedback entries");

        // Delete receipt items then receipts
        $receiptIds = Receipt::where('receipt_number', 'like', 'RCP-%')->pluck('id');
        $itemsDeleted = ReceiptItem::whereIn('receipt_id', $receiptIds)->delete();
        $receiptsDeleted = Receipt::where('receipt_number', 'like', 'RCP-%')->delete();
        $deleted += $receiptsDeleted;
        $this->line("  ✅ Deleted {$itemsDeleted} receipt items and {$receiptsDeleted} receipts");

        // Delete prescriptions
        $prescriptionsDeleted = Prescription::where('notes', 'like', '%Test prescription for analytics%')->delete();
        $deleted += $prescriptionsDeleted;
        $this->line("  ✅ Deleted {$prescriptionsDeleted} prescriptions");

        // Delete reservations
        $reservationsDeleted = Reservation::where('notes', 'like', '%Test reservation for analytics%')->delete();
        $deleted += $reservationsDeleted;
        $this->line("  ✅ Deleted {$reservationsDeleted} reservations");

        // Delete appointments
        $appointmentsDeleted = Appointment::where('notes', 'like', '%Test appointment for analytics%')->delete();
        $deleted += $appointmentsDeleted;
        $this->line("  ✅ Deleted {$appointmentsDeleted} appointments");

        // Delete test patients last (after all related data is deleted)
        $patientsDeleted = User::where('email', 'like', '%@testpatient.com')->delete();
        $deleted += $patientsDeleted;
        $this->line("  ✅ Deleted {$patientsDeleted} test patients");

        $this->newLine();
        $this->info("✅ Successfully deleted {$deleted} test records!");
        
        return 0;
    }
}

