-- Product Description Updates
-- Generated: 2025-11-30 06:52:54
-- SQL File: c:\Users\admin\Downloads\everbright_optical-1 (1).sql

UPDATE `products` SET `description` = 'Frame 101 - Stylish eyeglass frames, featuring modern design and durable construction. Contemporary design, versatile design suitable for all occasions Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 1;
UPDATE `products` SET `description` = 'Frame 2 - Stylish eyeglass frames, featuring modern design and durable construction. Elegant styling, perfect for professional and casual settings Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 2;
UPDATE `products` SET `description` = 'Frame1fh - Stylish eyeglass frames, featuring modern design and durable construction. Contemporary design, perfect for professional and casual settings Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 3;
UPDATE `products` SET `description` = 'Frame 1 - Stylish eyeglass frames, featuring modern design and durable construction. Contemporary design, perfect for professional and casual settings Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 4;
UPDATE `products` SET `description` = 'Frame 2 - Stylish eyeglass frames, featuring modern design and durable construction. Elegant styling, perfect for professional and casual settings Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 5;
UPDATE `products` SET `description` = 'Frame 3 - Stylish eyeglass frames, featuring modern design and durable construction. Contemporary design, perfect for professional and casual settings Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 6;
UPDATE `products` SET `description` = 'Frame 4 - Stylish eyeglass frames, featuring modern design and durable construction. Elegant styling, ideal for everyday lifestyle use Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 7;
UPDATE `products` SET `description` = 'Frame 5 - Stylish eyeglass frames, featuring modern design and durable construction. Contemporary design, ideal for everyday lifestyle use Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 8;
UPDATE `products` SET `description` = 'Frame 6 - Stylish eyeglass frames, featuring modern design and durable construction. Elegant styling, ideal for everyday lifestyle use Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 9;
UPDATE `products` SET `description` = 'Frame 7 - Stylish eyeglass frames, featuring modern design and durable construction. Contemporary design, ideal for everyday lifestyle use Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 10;
UPDATE `products` SET `description` = 'Frame 8 - Stylish eyeglass frames, featuring modern design and durable construction. Elegant styling, versatile design suitable for all occasions Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 11;
UPDATE `products` SET `description` = 'Frame 9 - Stylish eyeglass frames, featuring modern design and durable construction. Contemporary design, versatile design suitable for all occasions Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 12;
UPDATE `products` SET `description` = 'Frame 10 - Stylish eyeglass frames, featuring modern design and durable construction. Elegant styling, versatile design suitable for all occasions Premium eyewear optical frames designed to enhance your vision while complementing your personal style.' WHERE `id` = 13;
UPDATE `products` SET `description` = 'Contact Lense 1 - High-quality contact lenses designed for comfort and clarity. Perfect for daily wear with excellent breathability and moisture retention. These lenses provide superior vision correction while maintaining optimal eye health and comfort throughout the day. Premium contact lens solution for your vision needs.' WHERE `id` = 14;
UPDATE `products` SET `description` = 'Contact Lense 2 - High-quality contact lenses designed for comfort and clarity. Perfect for daily wear with excellent breathability and moisture retention. These lenses provide superior vision correction while maintaining optimal eye health and comfort throughout the day. Premium contact lens solution for your vision needs.' WHERE `id` = 15;
UPDATE `products` SET `description` = 'Contact Lense 3 - High-quality contact lenses designed for comfort and clarity. Perfect for daily wear with excellent breathability and moisture retention. These lenses provide superior vision correction while maintaining optimal eye health and comfort throughout the day. Premium contact lens solution for your vision needs.' WHERE `id` = 16;
UPDATE `products` SET `description` = 'Contact Lense 4 - High-quality contact lenses designed for comfort and clarity. Perfect for daily wear with excellent breathability and moisture retention. These lenses provide superior vision correction while maintaining optimal eye health and comfort throughout the day. Premium contact lens solution for your vision needs.' WHERE `id` = 17;
UPDATE `products` SET `description` = 'sa - Premium eyewear product featuring quality construction and comfortable design. Perfect for your vision needs with excellent durability and style. Premium optical product designed to enhance your vision and complement your personal style.' WHERE `id` = 18;
